---
title: "Americas COVID19 Cases and Deaths; Rate of doubling."
author: Professor John W Pickering, Univeristy of Otago Christchurch, New Zealand
date: "`r format(Sys.time(), '%d %B, %Y')` NZST"
output:
    pdf_document:
        toc: true
        toc_depth: 3

---
```{r libraries, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
library(tidyverse)
library(ggrepel)
library(lubridate)
library(rms)
library(splines)

load("CASES Greater 100.Rdata")
load("DEATHS Greater 10.Rdata")


```
\newpage  

# CASES
```{r , echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}

df_g <- df_100[df_100$location == "Americas",] %>% 
  filter(!is.na(country))

```


```{r , echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height = 4}
g_cases_separate <- ggplot() +
  geom_smooth(data = df_g, 
              aes(x =  ndays, y = dbl), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
              #formula = y ~ splines::bs(x, df = 4),
             # formula = y ~ rcs(x, nk = 2),
              se = TRUE,
              alpha = 0.85, 
              size = 2) +
  geom_line(data = df_g, aes(x = ndays, y = dbl, colour = country), alpha = 0.6, size = 0.5) +
  geom_point(data = df_g, aes(x = ndays, y = dbl, colour = country), alpha = 0.6, size = 0.5) +

  scale_y_log10(breaks = c(0.1,1,3,10,30, 100,300, 1000,3000), labels = c("0.1","1","3", "10","30","100","300","1000","3000")) +
  
  xlab("Number of days since 100th case") + ylab("Number of days for doubling") +
  coord_cartesian(ylim = c(1,30)) +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "seashell2"),
        panel.grid = element_line(colour = "grey80"),
        panel.grid.minor = element_blank()) 

g_cases_separate <- g_cases_separate + 
  facet_wrap(~ country, ncol = 3) + 
  ggtitle("Americas 5 April 2020", subtitle = "Author: JW Pickering; Data: John Hopkins University")

number_rows = ceiling(length(unique(df_g$country))/3)

ggsave(g_cases_separate, filename = "20-04-05 Americas Cases.jpg", width = 210  , height = 20 + 40 * number_rows , units = "mm")
(g_cases_separate)
```

\newpage

# Graphs with comparisons to all countries

```{r , echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height = 4}
df_g2 <- df_100 %>% 
  select(country, ndays,dbl, max_ndays) %>% 
  rename(z = "country") %>% 
  mutate(label = case_when(
    z == "Italy" & !is.na(max_ndays) ~ "Italy", 
    z == "China" & !is.na(max_ndays) ~ "China",
    z == "Korea, South" & !is.na(max_ndays) ~ "South Korea",
    z == "US" & !is.na(max_ndays) ~ "USA",
    TRUE ~ "NA"))

df_g3 <- df_g2 %>% 
  filter(z == "Italy" | z == "China" | z == "Korea, South"  | z == "US")

g_cases_separate <- ggplot() +
    geom_smooth(data = df_g2, 
              aes(x =  ndays, y = dbl, group = z), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
               se = FALSE,
              alpha = 0.35, 
              size = 0.5,
              colour = "grey70") +
    geom_smooth(data = df_g3, 
              aes(x =  ndays, y = dbl, group = z), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
               se = FALSE,
              alpha = 0.35, 
              size = 0.5,
              colour = "grey40") +
  
    geom_smooth(data = df_g, 
              aes(x =  ndays, y = dbl, group = country), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
              se = FALSE,
              alpha = 0.85, 
              size = 1) +
  geom_text(data = df_g3[df_g3$label != "NA",], aes(x =  max_ndays + 3, y = dbl, label = label), size = 2) +
  scale_y_log10(breaks = c(0.1,1,3,10,30, 100,300, 1000,3000), labels = c("0.1","1","3", "10","30","100","300","1000","3000")) +
  
  xlab("Number of days since 100th case") + ylab("Number of days for doubling") +
  coord_cartesian(ylim = c(1,3000), xlim = c(0,80)) +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "seashell2"),
        panel.grid = element_line(colour = "grey80"),
        panel.grid.minor = element_blank()) 

g_cases_separate <- g_cases_separate + 
  facet_wrap(~ country, ncol = 3) + 
  ggtitle("Americas 5 April 2020", subtitle = "Author: JW Pickering; Data: John Hopkins University")

number_rows = ceiling(length(unique(df_g$country))/3)

ggsave(g_cases_separate, filename = "20-04-05 Americas Cases Comparisons.jpg", width = 210  , height = 20 + 40 * number_rows , units = "mm")
(g_cases_separate)
```

# DEATHS
```{r , echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}

df_g <- df_10[df_10$location == "Americas",] %>% 
  filter(!is.na(country))
# Correct one very odd value

```

```{r , echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height = 4}

g_deaths_separate <- ggplot() +
  geom_smooth(data = df_g, 
              aes(x =  ndays, y = dbl), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
              #formula = y ~ splines::bs(x, df = 4),
             # formula = y ~ rcs(x, nk = 2),
              se = TRUE,
              alpha = 0.85, 
              size = 2) +
  geom_line(data = df_g, aes(x = ndays, y = dbl, colour = country), alpha = 0.6, size = 0.5) +
  geom_point(data = df_g, aes(x = ndays, y = dbl, colour = country), alpha = 0.6, size = 0.5) +

  scale_y_log10(breaks = c(0.1,1,3,10,30, 100,300, 1000,3000), labels = c("0.1","1","3", "10","30","100","300","1000","3000")) +
  
  xlab("Number of days since 10th death") + ylab("Number of days for doubling") +
  coord_cartesian(ylim = c(0.25,30)) +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "seashell2"),
        panel.grid = element_line(colour = "grey80"),
        panel.grid.minor = element_blank()) 

g_deaths_separate <- g_deaths_separate + 
  facet_wrap(~ country, ncol = 3) + 
  ggtitle("Americas 5 April 2020", subtitle = "Author: JW Pickering; Data: John Hopkins University")

ggsave(g_deaths_separate, filename = "20-04-05 Americas Deaths.jpg", width = 210  , height = 20 + 40 * number_rows , units = "mm")
(g_deaths_separate)
```

\newpage

```{r , echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height = 4}
df_g2 <- df_10 %>% 
  select(country, ndays,dbl, max_ndays) %>% 
  rename(z = "country") %>% 
  mutate(label = case_when(
    z == "Italy" & !is.na(max_ndays) ~ "Italy", 
    z == "China" & !is.na(max_ndays) ~ "China",
    z == "Korea, South" & !is.na(max_ndays) ~ "South Korea",
    z == "US" & !is.na(max_ndays) ~ "USA",
    TRUE ~ "NA"))

df_g3 <- df_g2 %>% 
  filter(z == "Italy" | z == "China" | z == "Korea, South"  | z == "US")

g_deaths_separate <- ggplot() +
    geom_smooth(data = df_g2, 
              aes(x =  ndays, y = dbl, group = z), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
               se = FALSE,
              alpha = 0.35, 
              size = 0.5,
              colour = "grey70") +
    geom_smooth(data = df_g3, 
              aes(x =  ndays, y = dbl, group = z), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
               se = FALSE,
              alpha = 0.35, 
              size = 0.5,
              colour = "grey40") +
  
    geom_smooth(data = df_g, 
              aes(x =  ndays, y = dbl, group = country), 
              method = "lm",
              formula = y ~ splines::ns(x, df = 3),
              se = FALSE,
              alpha = 0.85, 
              size = 1) +
  geom_text(data = df_g3[df_g3$label != "NA",], aes(x =  max_ndays + 3, y = dbl, label = label, size = 2)) +
  scale_y_log10(breaks = c(0.1,1,3,10,30, 100,300, 1000,3000), labels = c("0.1","1","3", "10","30","100","300","1000","3000")) +
  
  xlab("Number of days since 10th death") + ylab("Number of days for doubling") +
  coord_cartesian(ylim = c(0.75,1000), xlim = c(0,80)) +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "seashell2"),
        panel.grid = element_line(colour = "grey80"),
        panel.grid.minor = element_blank()) 

g_deaths_separate <- g_deaths_separate + 
  facet_wrap(~ country, ncol = 3) + 
  ggtitle("Americas 5 April 2020", subtitle = "Author: JW Pickering; Data: John Hopkins University")

number_rows = ceiling(length(unique(df_g$country))/3)

ggsave(g_deaths_separate, filename = "20-04-05 Americas deaths Comparisons.jpg", width = 210  , height = 20 + 40 * number_rows , units = "mm")
(g_deaths_separate)
```